export const designers = [
  {
    id: "1",
    name: "Yuki Tanaka",
    studio: "Yuki Tanaka Studio",
    location: "Kyoto, Japan",
    founded: 2018,
    bio: "Trained in traditional Japanese textile arts, Yuki bridges ancestral techniques with contemporary minimalism. Each piece is made to order in her Kyoto studio, using natural dyes and ethically sourced fabrics.",
    philosophy: "Clothing should feel like a second skin — something that breathes with you, carries memory, and grows more beautiful with wear.",
    accent: "#4A7C59",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
    banner: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1400&q=85",
    followers: 2840,
    featured: true,
  },
  {
    id: "2",
    name: "Clara Voss",
    studio: "Voss Atelier",
    location: "Berlin, Germany",
    founded: 2020,
    bio: "Clara studied fashion design at Parsons before returning to her hometown. Her work focuses on deconstructed tailoring with sustainable wool sourced from small German farms.",
    philosophy: "Structure is freedom. A well-tailored piece gives you confidence to move through the world exactly as you are.",
    accent: "#8B6F4E",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b829?w=400&q=80",
    banner: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1400&q=85",
    followers: 1920,
    featured: false,
  },
  {
    id: "3",
    name: "Amara Diallo",
    studio: "Amara Studio",
    location: "Lagos, Nigeria",
    founded: 2019,
    bio: "Amara draws from West African textile traditions, reimagining them for a global audience without losing their cultural roots or ethical integrity.",
    philosophy: "Every pattern has a story. My work is a conversation between generations of African craftsmanship and the modern world.",
    accent: "#C4884F",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    banner: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1400&q=85",
    followers: 3210,
    featured: false,
  },
  {
    id: "4",
    name: "Sol Martínez",
    studio: "Sol Studio",
    location: "Barcelona, Spain",
    founded: 2021,
    bio: "Sol works with deadstock fabrics from Barcelona's historic textile district, transforming surplus into sculptural knitwear. Zero waste is not a constraint — it's a creative challenge.",
    philosophy: "The best luxury is knowing exactly where your clothes come from and that no harm was done in making them.",
    accent: "#6B5B8E",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    banner: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1400&q=85",
    followers: 1650,
    featured: false,
  },
];

export const products = [
  {
    id: "p1",
    designerId: "1",
    designerName: "Yuki Tanaka",
    name: "Indigo Linen Pleated Shirt",
    description: "Hand-dyed with natural indigo extracted from plants grown near Yuki's studio, each shirt carries its own unique color variation — a mark of its handmade origin. The asymmetric pleats on the back create gentle movement with every step.\n\nCut from 180gsm linen, the fabric is pre-washed to ensure minimal shrinkage and a naturally worn-in feel from day one. The relaxed silhouette works equally well tucked or untucked.",
    price: 420000,
    currency: "IDR",
    category: "Tops",
    stock: "pre-order",
    stockCount: 12,
    totalEdition: 50,
    dropDate: "April 20, 2026",
    productionClose: "March 28, 2026",
    shipsBy: "April 20, 2026",
    leadTime: "3–4 weeks",
    badge: "Pre-order",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=85",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=85",
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=85",
    ],
    materials: [
      { name: "100% Linen", source: "Sourced from suppliers in Normandy, France" },
      { name: "Natural Indigo Dye", source: "Locally grown and extracted, Kyoto" },
      { name: "Shell Buttons", source: "Recycled oyster shell, certified sustainable" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Deep Indigo", hex: "#1B2D4F" },
      { name: "Faded Blue", hex: "#7B95B4" },
      { name: "Natural", hex: "#E8DFD0" },
    ],
    inspiration: "Inspired by the morning light filtering through the washi paper screens of a traditional Kyoto machiya. The color gradients in the natural indigo dyeing mirror this quality of diffused light.",
    processImages: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
    ],
    featured: true,
  },
  {
    id: "p2",
    designerId: "2",
    designerName: "Clara Voss",
    name: "Wool Tailored Overshirt",
    description: "A deconstructed take on the classic tailored shirt, rendered in 100% merino wool from small farms in the Bavarian Alps. The intentional absence of lining gives the piece a sculptural drape while maintaining warmth.\n\nThe slightly exaggerated shoulder line and dropped hem create a silhouette that sits beautifully over trousers or jeans alike.",
    price: 680000,
    currency: "IDR",
    category: "Outerwear",
    stock: "in-stock",
    stockCount: 8,
    totalEdition: 30,
    shipsBy: "March 18, 2026",
    badge: "Limited Edition",
    images: [
      "https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=800&q=85",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=85",
    ],
    materials: [
      { name: "100% Merino Wool", source: "Bavarian Alps small farms, Germany" },
      { name: "Hand-stitched details", source: "Made in Berlin atelier" },
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Warm Oat", hex: "#C9B99A" },
      { name: "Charcoal Mist", hex: "#5C6470" },
      { name: "Cream", hex: "#F0EAD6" },
    ],
    inspiration: "Berlin's layered architectural history — old walls exposed beneath new construction — informs the deconstructed structure of this piece.",
    processImages: [],
    featured: true,
  },
  {
    id: "p3",
    designerId: "3",
    designerName: "Amara Diallo",
    name: "Adire Wrap Dress",
    description: "Made using the traditional Yoruba indigo-dyeing technique of adire, this wrap dress features hand-drawn wax-resist patterns applied before dyeing. No two pieces are identical — the variation is the point.\n\nThe fabric is a lightweight cotton-linen blend chosen for the Nigerian climate, with a globally wearable silhouette.",
    price: 560000,
    currency: "IDR",
    category: "Dresses",
    stock: "made-to-order",
    stockCount: null,
    shipsBy: "5 weeks from order",
    badge: "Made-to-Order",
    images: [
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=85",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=85",
    ],
    materials: [
      { name: "Cotton-Linen Blend", source: "Ethically woven in Kano, Nigeria" },
      { name: "Natural Indigo Dye", source: "Traditional Yoruba recipe, Lagos" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Midnight Indigo", hex: "#0D1B4B" },
      { name: "Ocean Floor", hex: "#2B3F6C" },
    ],
    inspiration: "The geometric patterns echo the adinkra symbols of West African textiles, reinterpreted through Amara's contemporary lens.",
    processImages: [],
    featured: false,
  },
  {
    id: "p4",
    designerId: "4",
    designerName: "Sol Martínez",
    name: "Deadstock Ribbed Cardigan",
    description: "Knitted from a deadstock wool blend sourced from the historic Clot district of Barcelona, this oversized cardigan would otherwise have gone to waste. Each run uses whatever color deadstock is available — making every edition truly one-of-a-kind.\n\nThe wide rib structure adds texture and warmth while keeping the silhouette relaxed and layerable.",
    price: 490000,
    currency: "IDR",
    category: "Knits",
    stock: "in-stock",
    stockCount: 5,
    totalEdition: 20,
    shipsBy: "March 15, 2026",
    badge: "Limited Edition",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=85",
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=85",
    ],
    materials: [
      { name: "Deadstock Wool Blend", source: "Reclaimed from Barcelona textile district" },
      { name: "Natural shell buttons", source: "Vintage stock, reused" },
    ],
    sizes: ["One Size (S–L)"],
    colors: [
      { name: "Dusty Mauve", hex: "#C4A0A0" },
      { name: "Warm Sand", hex: "#D4C5A9" },
    ],
    inspiration: "Scarcity as abundance — finding beauty and utility in what already exists.",
    processImages: [],
    featured: false,
  },
  {
    id: "p5",
    designerId: "1",
    designerName: "Yuki Tanaka",
    name: "Sashiko Wide Trousers",
    description: "Sashiko is a traditional Japanese form of functional embroidery, used historically to reinforce worn fabric. These wide-leg trousers feature sashiko stitching along the seams as both structure and decoration.\n\nMade in a heavy cotton twill that softens beautifully with washing, with a comfortable elasticated waist.",
    price: 380000,
    currency: "IDR",
    category: "Bottoms",
    stock: "pre-order",
    stockCount: 18,
    totalEdition: 60,
    dropDate: "May 5, 2026",
    productionClose: "April 10, 2026",
    shipsBy: "May 5, 2026",
    badge: "Pre-order",
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=85",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=85",
    ],
    materials: [
      { name: "Heavy Cotton Twill", source: "Woven in Okayama Prefecture, Japan" },
      { name: "Cotton Sashiko Thread", source: "Hand-spun, natural undyed" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Natural White", hex: "#F2EDE4" },
      { name: "Walnut", hex: "#6B4F3A" },
    ],
    inspiration: "The philosophy of wabi-sabi — finding beauty in imperfection and the marks of use.",
    processImages: [],
    featured: false,
  },
  {
    id: "p6",
    designerId: "2",
    designerName: "Clara Voss",
    name: "Structured Linen Blazer",
    description: "A season-less blazer cut from unlined Normandy linen, structured without being stiff. The single-button closure and rounded lapels give a slightly feminine softness to an otherwise architectural silhouette.\n\nMade to order in Berlin in your choice of natural, stone, or slate colorways.",
    price: 750000,
    currency: "IDR",
    category: "Outerwear",
    stock: "made-to-order",
    stockCount: null,
    shipsBy: "4 weeks from order",
    badge: "Made-to-Order",
    images: [
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=85",
      "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=800&q=85",
    ],
    materials: [
      { name: "100% Linen", source: "Normandy, France" },
      { name: "Recycled Polyester Lining Strips", source: "EU certified recycled content" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Natural", hex: "#D4C5A9" },
      { name: "Slate", hex: "#708090" },
      { name: "Stone", hex: "#B2A99A" },
    ],
    inspiration: "The spatial clarity of Bauhaus architecture — functional, honest, beautiful.",
    processImages: [],
    featured: false,
  },
  {
    id: "p7",
    designerId: "3",
    designerName: "Amara Diallo",
    name: "Woven Cotton Maxi Dress",
    description: "A sweeping maxi silhouette woven from ethically sourced cotton in Lagos. The open weave creates natural breathability while the bold geometric border — a reinterpretation of Yoruba kente — adds unmistakable presence.\n\nCut generously for ease of movement, this dress works from day to evening.",
    price: 620000,
    currency: "IDR",
    category: "Dresses",
    stock: "made-to-order",
    stockCount: null,
    shipsBy: "5 weeks from order",
    badge: "Made-to-Order",
    images: [
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=85",
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=85",
    ],
    materials: [
      { name: "Hand-Woven Cotton", source: "Ethically produced in Lagos, Nigeria" },
      { name: "Natural Dye Border", source: "Traditional Yoruba pigments" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Terracotta & Cream", hex: "#C4884F" },
      { name: "Midnight & Gold", hex: "#0D1B4B" },
    ],
    inspiration: "The rhythm of weaving as meditation — each thread intentional.",
    processImages: [],
    featured: false,
  },
  {
    id: "p8",
    designerId: "4",
    designerName: "Sol Martínez",
    name: "Merino Ribbed Turtleneck",
    description: "Knitted in a wide-rib structure from deadstock merino sourced in Barcelona's Clot district. The oversized turtleneck and dropped shoulder create an effortlessly relaxed silhouette that layers beautifully.\n\nEach piece uses leftover yarn from luxury fashion houses — making it truly circular.",
    price: 445000,
    currency: "IDR",
    category: "Knits",
    stock: "in-stock",
    stockCount: 7,
    totalEdition: 25,
    shipsBy: "March 22, 2026",
    badge: "Limited Edition",
    images: [
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=85",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=85",
    ],
    materials: [
      { name: "Deadstock Merino Wool", source: "Reclaimed from Barcelona luxury mills" },
    ],
    sizes: ["XS/S", "M/L", "XL/2XL"],
    colors: [
      { name: "Ecru", hex: "#F0EAD6" },
      { name: "Forest", hex: "#3B5E45" },
      { name: "Burgundy", hex: "#6B2737" },
    ],
    inspiration: "Luxury reimagined — the same quality, without the waste.",
    processImages: [],
    featured: false,
  },
];

export const categories = [
  { id: "outerwear", name: "Outerwear", image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=85" },
  { id: "tops", name: "Tops", image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=85" },
  { id: "bottoms", name: "Bottoms", image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&q=85" },
  { id: "dresses", name: "Dresses", image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=85" },
  { id: "knits", name: "Knits", image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=85" },
  { id: "accessories", name: "Accessories", image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&q=85" },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
}

export function getProductsByDesigner(designerId: string) {
  return products.filter((p) => p.designerId === designerId);
}

export function getDesignerById(id: string) {
  return designers.find((d) => d.id === id);
}

export function getProductById(id: string) {
  return products.find((p) => p.id === id);
}
